const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const ids = new Set(Array.from(html.matchAll(/\bid="([^"]+)"/g), match => match[1]));
const nodes = new Map();
const storage = new Map();
let downloaded = '';

class FakeNode {
  constructor(tag, id) {
    this.tag = tag;
    this.id = id;
    this.children = [];
    this.arcCalls = [];
    this.listeners = {};
    this.value = '';
    this.hidden = false;
    this.disabled = false;
    this.checked = true;
    this.textContent = '';
    this.style = {};
    this.classList = { toggle() {} };
  }
  addEventListener(name, callback) { (this.listeners[name] ||= []).push(callback); }
  async fire(name, event = {}) {
    for (const callback of this.listeners[name] || []) await callback.call(this, Object.assign({ target: this, offsetX: 80, pointerId: 1, preventDefault() {} }, event));
  }
  appendChild(child) { this.children.push(child); return child; }
  append(...items) { this.children.push(...items); }
  replaceChildren(...items) { this.children = items; }
  remove() {}
  setAttribute() {}
  scrollIntoView() {}
  getBoundingClientRect() { return { left: 0, top: 0, width: 900, height: 430 }; }
  setPointerCapture() { this.captured = true; }
  hasPointerCapture() { return !!this.captured; }
  releasePointerCapture() { this.captured = false; }
  click() { downloaded = this.download || ''; }
  getContext() {
    return {
      setTransform() {}, clearRect() {}, fillRect() {}, beginPath() {}, moveTo() {}, lineTo() {}, stroke() {}, arc: (...args) => { this.arcCalls.push(args); }, fill() {}, setLineDash() {},
      save() {}, restore() {}, translate() {}, scale() {}, rotate() {}, rect() {}, clip() {}, strokeRect() {}, ellipse() {}, closePath() {}, drawImage() {},
      createRadialGradient() { return { addColorStop() {} }; },
      fillText() {}, measureText(value) { return { width: String(value).length * 10 }; }
    };
  }
  toDataURL() { return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9WAaEAAAAASUVORK5CYII='; }
  toBlob(callback) { callback({ type: 'image/png' }); }
}

const ratioNodes = Array.from(html.matchAll(/data-ratio="([^"]+)"/g), match => { const node = new FakeNode('button'); node.dataset = { ratio: match[1] }; return node; });
const backgroundNodes = Array.from(html.matchAll(/data-bg="([^"]+)"/g), match => { const node = new FakeNode('button'); node.dataset = { bg: match[1] }; return node; });
for (const id of ids) nodes.set(id, new FakeNode('element', id));
const document = {
  getElementById(id) { return nodes.get(id) || null; },
  createElement(tag) { return new FakeNode(tag); },
  createTextNode(text) { const node = new FakeNode('text'); node.textContent = text; return node; },
  createDocumentFragment() { return new FakeNode('fragment'); },
  querySelectorAll(selector) { return selector === '[data-ratio]' ? ratioNodes : selector === '[data-bg]' ? backgroundNodes : []; },
  fonts: { add() {} },
  head: new FakeNode('head'),
  body: new FakeNode('body')
};
const window = {
  localStorage: { getItem: key => storage.get(key) || null, setItem: (key, value) => storage.set(key, value), removeItem: key => storage.delete(key) },
  devicePixelRatio: 1,
  Image: class { set src(value) { if (value.includes('CORRUPT')) { this.onerror(); return; } this.width = 400; this.height = 300; this.onload(); } },
  ResizeObserver: class { observe() {} },
  addEventListener() {}
};
window.FontFace = class {
  constructor(family, source) { this.family = family; this.source = source; }
  load() { return this.source.includes('CORRUPT') ? Promise.reject(new Error('bad font')) : Promise.resolve(this); }
};
class FileReader { readAsDataURL(file) { if (file.defer) { file.finish = () => { this.result = file.data; this.onload(); }; return; } this.result = file.data; this.onload(); } }
const context = { window, document, URLSearchParams, Blob, FileReader, URL: { createObjectURL: () => 'blob:test', revokeObjectURL() {} }, setTimeout: callback => callback(), clearTimeout() {} };
vm.createContext(context);
for (const [, file] of html.matchAll(/<script defer src="([^"]+)"/g)) {
  vm.runInContext(fs.readFileSync(path.join(root, file.split('?')[0]), 'utf8'), context, { filename: file });
}

(async () => {
  await nodes.get('tab-csv').fire('click');
  await nodes.get('load-sample').fire('click');
  const exampleBars = window.YINK.parseCsv(fs.readFileSync(path.join(root, 'examples/sample.csv'), 'utf8'));
  assert.equal(JSON.stringify(window.YINK.currentData.bars), JSON.stringify(exampleBars));
  assert.equal(window.YINK.currentData.security.symbol, 'YINK-DEMO');
  assert.match(nodes.get('status').textContent, /示例数据已加载/);
  nodes.get('csv-file').files = [{ size: 500, text: async () => fs.readFileSync(path.join(root, 'examples/sample.csv'), 'utf8') }];
  await nodes.get('csv-file').fire('change');
  assert.equal(nodes.get('csv-symbol').value, '');
  assert.equal(nodes.get('csv-name').value, '');
  assert.equal(nodes.get('start-date').value, '2026-09-01');
  await nodes.get('load-button').fire('click');
  assert.equal(nodes.get('studio-section').hidden, false);
  assert.equal(window.YINK.currentData.bars.length, 3);
  assert.equal(nodes.get('bar-count-label').textContent, 'DAILY BARS');
  const validData = window.YINK.currentData;
  const originalCsvIdentity = validData.identity;
  const damagedData = JSON.parse(JSON.stringify(validData));
  damagedData.bars[0].low = -1;
  assert.throws(() => window.YINK.restoreSessionData(damagedData), /无效数值/);
  assert.equal(window.YINK.currentData, validData);
  assert.throws(() => window.YINK.restoreSessionData({ ...validData, range: { start: 'bad', end: '2026-09-03' } }), /有效的开始和结束日期/);
  assert.equal(window.YINK.currentData, validData);
  nodes.get('csv-currency').value = 'HKD';
  await nodes.get('csv-currency').fire('change');
  assert.equal(window.YINK.currentData.security.currency, 'HKD');
  nodes.get('kline-interval').value = 'week';
  await nodes.get('kline-interval').fire('change');
  await nodes.get('load-button').fire('click');
  assert.equal(window.YINK.currentData.interval, 'week');
  assert.equal(window.YINK.currentData.bars.length, 1);
  assert.equal(nodes.get('bar-count-label').textContent, 'WEEKLY BARS');
  assert.match(nodes.get('status').textContent, /至少需要两根 K 线/);
  assert.equal(window.YINK.currentData.identity, originalCsvIdentity);
  const savedWeekly = JSON.parse(storage.get('yink.session.v1')).data;
  assert.equal(savedWeekly.rawBars.length, 3);
  await nodes.get('chart-canvas').fire('pointerdown', { offsetX: 80 });
  await nodes.get('chart-canvas').fire('pointerup', { offsetX: 80 });
  await nodes.get('mark-buy').fire('click');
  await nodes.get('mark-sell').fire('click');
  let quantityInput = nodes.get('trade-events').children[0].children[2].children[0];
  quantityInput.value = '1';
  await quantityInput.fire('change');
  quantityInput = nodes.get('trade-events').children[1].children[2].children[0];
  quantityInput.value = '1';
  await quantityInput.fire('change');
  assert.equal(nodes.get('make-poster').disabled, true);
  assert.ok(nodes.get('trade-result').children.some(child => /至少需要两根 K 线/.test(child.textContent)));
  const brokenRaw = JSON.parse(JSON.stringify(savedWeekly));
  brokenRaw.rawBars[0].close = 999;
  window.YINK.restoreSessionData(brokenRaw);
  assert.equal(window.YINK.currentData.bars.length, 1);
  assert.match(nodes.get('status').textContent, /重新导入原始 CSV/);
  window.YINK.restoreSessionData(savedWeekly);
  assert.equal(window.YINK.currentData.interval, 'week');
  const storeSession = window.localStorage.setItem;
  window.localStorage.setItem = (key, value) => {
    if (key === 'yink.session.v1' && JSON.parse(value).data.rawBars) throw new Error('quota');
    storeSession(key, value);
  };
  nodes.get('capital').value = '100';
  await nodes.get('capital').fire('input');
  assert.equal(JSON.parse(storage.get('yink.session.v1')).data.rawBars, undefined);
  assert.match(nodes.get('session-save-status').textContent, /刷新后切换时间级别需重新导入/);
  window.localStorage.setItem = storeSession;
  nodes.get('start-date').value = '2026-01-01';
  nodes.get('kline-interval').value = 'auto';
  await nodes.get('kline-interval').fire('change');
  await nodes.get('load-button').fire('click');
  assert.equal(window.YINK.currentData.interval, 'day');
  assert.equal(window.YINK.currentData.bars.length, 3);
  assert.match(nodes.get('status').textContent, /自动模式已回退到日 K/);
  nodes.get('start-date').value = '2026-09-01';
  nodes.get('kline-interval').value = 'day';
  await nodes.get('kline-interval').fire('change');
  await nodes.get('load-button').fire('click');
  assert.equal(window.YINK.currentData.interval, 'day');
  assert.equal(window.YINK.currentData.bars.length, 3);
  assert.equal(nodes.get('make-poster').disabled, false);
  assert.match(nodes.get('trade-result').textContent, /原始 K 线贴图/);
  assert.equal(nodes.get('buy-price').disabled, true);
  assert.equal(nodes.get('sell-price').disabled, true);
  await nodes.get('make-poster').fire('click');
  assert.equal(nodes.get('style-section').hidden, false);
  assert.equal(nodes.get('kline-crop').value, 'range');
  assert.equal(nodes.get('kline-buy-marker').disabled, true);
  assert.equal(nodes.get('kline-profit-mode').disabled, true);
  assert.equal(nodes.get('open-classic').disabled, true);
  assert.equal(window.YINK.getTradeSnapshot().trade, null);
  nodes.get('kline-crop').value = 'custom';
  nodes.get('kline-crop-start').value = '2026-09-01';
  nodes.get('kline-crop-end').value = '2026-09-02';
  assert.equal(window.YINK.getTradeSnapshot({ mode: 'custom', start: '2026-09-01', end: '2026-09-02' }).bars.length, 2);
  nodes.get('kline-crop').value = 'range';
  await nodes.get('open-editor').fire('click');
  assert.equal(nodes.get('editor-section').hidden, false);
  const rawDesign = JSON.parse(storage.get('yink.editor.v1'));
  assert.equal(rawDesign.source.trade, null);
  assert.equal(rawDesign.layers.find(layer => layer.type === 'kline').trade, null);
  assert.equal(rawDesign.layers.some(layer => layer.binding === 'returnPct'), false);
  assert.equal(nodes.get('editor-add-prices').disabled, true);
  assert.equal(nodes.get('editor-add-profit').disabled, true);
  await nodes.get('editor-layers').children.find(row => row.children[0].textContent.includes('原始 K 线')).children[0].fire('click');
  assert.equal(nodes.get('prop-kline-buy-marker').disabled, true);
  assert.equal(nodes.get('prop-kline-profit-mode').disabled, true);
  assert.equal(nodes.get('prop-kline-mode').disabled, false);
  await nodes.get('kline-stylized-tab').fire('click');
  await nodes.get('ink-two-tab').fire('click');
  await Promise.resolve();
  assert.match(nodes.get('ink-style-status').textContent, /透明 2D 笔刷 v3/);
  assert.equal(nodes.get('ink2-markers').disabled, true);
  await nodes.get('open-editor').fire('click');
  const rawInkDesign = JSON.parse(storage.get('yink.editor.v1'));
  assert.equal(rawInkDesign.layers.find(layer => layer.type === 'kline').style.renderer, 'ink2');
  assert.equal(rawInkDesign.layers.find(layer => layer.type === 'kline').style.inkMarkers, false);
  assert.equal(rawInkDesign.layers.find(layer => layer.type === 'kline').trade, null);
  await nodes.get('editor-export').fire('click');
  assert.match(downloaded, /\.png$/);
  await nodes.get('editor-save-project').fire('click');
  assert.match(downloaded, /\.json$/);
  await nodes.get('ink-one-tab').fire('click');
  await nodes.get('kline-standard-tab').fire('click');
  const canvas = nodes.get('chart-canvas');
  const dateBeforePointer = nodes.get('selected-date').textContent;
  await canvas.fire('pointerdown', { offsetX: 80 });
  await canvas.fire('pointerdown', { offsetX: 800, pointerId: 2 });
  await canvas.fire('pointermove', { offsetX: 800, pointerId: 2 });
  await canvas.fire('pointerup', { offsetX: 800, pointerId: 2 });
  assert.equal(nodes.get('selected-date').textContent, dateBeforePointer);
  await canvas.fire('pointerup', { offsetX: 80 });
  assert.match(nodes.get('selected-date').textContent, /2026-09-01/);
  await nodes.get('mark-buy').fire('click');
  assert.equal(nodes.get('make-poster').disabled, true);
  assert.throws(() => window.YINK.getTradeSnapshot(), /请先标记 BUY 和 SELL/);
  await canvas.fire('pointerdown', { offsetX: 800 });
  await canvas.fire('pointercancel', { offsetX: 800 });
  assert.match(nodes.get('selected-date').textContent, /2026-09-01/);
  await canvas.fire('pointerdown', { offsetX: 800 });
  await canvas.fire('pointerup', { offsetX: 800 });
  await nodes.get('mark-sell').fire('click');
  nodes.get('sell-price').value = '230';
  await nodes.get('sell-price').fire('change');
  assert.equal(nodes.get('make-poster').disabled, false);
  nodes.get('capital').value = '10000';
  await nodes.get('capital').fire('input');
  await nodes.get('make-poster').fire('click');
  assert.equal(nodes.get('style-section').hidden, false);
  assert.equal(nodes.get('kline-standard-panel').hidden, false);
  nodes.get('editor-section').hidden = true;
  await nodes.get('kline-stylized-tab').fire('click');
  assert.equal(nodes.get('kline-standard-panel').hidden, true);
  assert.equal(nodes.get('kline-stylized-panel').hidden, false);
  nodes.get('ink-bleed').value = '2';
  await nodes.get('ink-bleed').fire('change');
  nodes.get('ink-buy-marker').value = 'ink-ring';
  await nodes.get('ink-buy-marker').fire('change');
  nodes.get('ink-sell-marker').value = 'ink-blot';
  await nodes.get('ink-sell-marker').fire('change');
  nodes.get('ink-marker-size').value = '16';
  await nodes.get('ink-marker-size').fire('change');
  await nodes.get('open-editor').fire('click');
  assert.equal(nodes.get('editor-section').hidden, false);
  const inkDesign = JSON.parse(storage.get('yink.editor.v1'));
  assert.equal(inkDesign.layers.find(layer => layer.type === 'kline').style.renderer, 'ink');
  assert.equal(inkDesign.layers.find(layer => layer.type === 'kline').style.surface, 'transparent');
  assert.equal(inkDesign.layers.find(layer => layer.type === 'kline').style.inkBleed, 2);
  assert.equal(inkDesign.layers.find(layer => layer.type === 'kline').style.buyMarker, 'ink-ring');
  assert.equal(inkDesign.layers.find(layer => layer.type === 'kline').style.sellMarker, 'ink-blot');
  assert.equal(inkDesign.layers.find(layer => layer.type === 'kline').style.markerSize, 16);
  await nodes.get('editor-layers').children.find(row => row.children[0].textContent.includes('交易 K 线')).children[0].fire('click');
  assert.equal(nodes.get('ink-properties').hidden, false);
  assert.equal(nodes.get('kline-properties').hidden, true);
  nodes.get('prop-ink-bleed').value = '0.5';
  await nodes.get('prop-ink-bleed').fire('change');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.find(layer => layer.type === 'kline').style.inkBleed, 0.5);
  nodes.get('prop-ink-line').checked = false;
  await nodes.get('prop-ink-line').fire('change');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.find(layer => layer.type === 'kline').style.inkLine, false);
  nodes.get('prop-ink-buy-marker').value = 'ink-stamp';
  await nodes.get('prop-ink-buy-marker').fire('change');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.find(layer => layer.type === 'kline').style.buyMarker, 'ink-stamp');
  nodes.get('prop-ink-buy-marker').value = 'image';
  await nodes.get('prop-ink-buy-marker').fire('change');
  assert.match(nodes.get('editor-status').textContent, /请先上传/);
  nodes.get('prop-ink-buy-image').files = [{ type: 'image/png', size: 100, data: 'data:image/png;base64,BBBB' }];
  await nodes.get('prop-ink-buy-image').fire('change');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.find(layer => layer.type === 'kline').style.buyMarker, 'image');
  nodes.get('prop-ink-buy-marker').value = 'ink-stamp';
  await nodes.get('prop-ink-buy-marker').fire('change');
  await nodes.get('ink-two-tab').fire('click');
  assert.equal(nodes.get('ink-two-controls').hidden, false);
  assert.equal(nodes.get('ink-one-controls').hidden, true);
  nodes.get('ink2-dryness').value = '2';
  await nodes.get('ink2-dryness').fire('change');
  await nodes.get('open-editor').fire('click');
  const ink2Project = JSON.parse(storage.get('yink.editor.v1'));
  const ink2Layer = ink2Project.layers.find(layer => layer.type === 'kline');
  assert.equal(ink2Layer.style.renderer, 'ink2');
  assert.equal(ink2Layer.style.mode, 'line');
  assert.equal(ink2Layer.style.strokeWidth, 1);
  assert.equal(ink2Layer.style.inkDryness, 2);
  assert.equal(window.YINK.EditorModel.validateDesign(ink2Project).layers.find(layer => layer.type === 'kline').style.renderer, 'ink2');
  await nodes.get('editor-layers').children.find(row => row.children[0].textContent.includes('交易 K 线')).children[0].fire('click');
  assert.equal(nodes.get('prop-ink-line-row').hidden, true);
  assert.equal(nodes.get('prop-ink2-dryness-row').hidden, false);
  nodes.get('prop-ink2-dryness').value = '1.5';
  await nodes.get('prop-ink2-dryness').fire('change');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.find(layer => layer.type === 'kline').style.inkDryness, 1.5);
  nodes.get('prop-ink2-ghost').checked = false;
  await nodes.get('prop-ink2-ghost').fire('change');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.find(layer => layer.type === 'kline').style.inkGhost, false);
  await nodes.get('editor-export').fire('click');
  assert.match(downloaded, /YINK-artwork/);
  await nodes.get('ink-one-tab').fire('click');
  await nodes.get('kline-standard-tab').fire('click');
  assert.equal(nodes.get('kline-standard-panel').hidden, false);
  assert.equal(nodes.get('kline-stylized-panel').hidden, true);
  const stickerPreview = window.YINK.showStyleStep;
  let previewUpdates = 0;
  window.YINK.showStyleStep = () => { previewUpdates++; stickerPreview(); };
  nodes.get('sell-price').value = '231';
  await nodes.get('sell-price').fire('change');
  assert.equal(previewUpdates, 1);
  nodes.get('sell-price').value = '0';
  await nodes.get('sell-price').fire('change');
  assert.equal(nodes.get('style-section').hidden, true);
  assert.equal(nodes.get('make-poster').disabled, true);
  nodes.get('sell-price').value = '230';
  await nodes.get('sell-price').fire('change');
  await nodes.get('make-poster').fire('click');
  window.YINK.showStyleStep = stickerPreview;
  await nodes.get('open-editor').fire('click');
  assert.equal(nodes.get('editor-section').hidden, false);
  assert.equal(nodes.get('layer-count').textContent, '6');
  const draftBeforeZoom = storage.get('yink.editor.v1');
  nodes.get('editor-zoom').value = '1.5';
  await nodes.get('editor-zoom').fire('change');
  assert.equal(nodes.get('editor-canvas-wrap').style.width, '975px');
  assert.equal(storage.get('yink.editor.v1'), draftBeforeZoom);
  nodes.get('editor-zoom').value = '1';
  await nodes.get('editor-zoom').fire('change');
  assert.equal(nodes.get('editor-canvas-wrap').style.width, '650px');
  await nodes.get('editor-add-prices').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.at(-1).text, '213.00  →  230.00');
  nodes.get('prop-name').value = '成交记录';
  await nodes.get('prop-name').fire('change');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.at(-1).binding, 'prices');
  nodes.get('sell-price').value = '231';
  await nodes.get('sell-price').fire('change');
  await nodes.get('open-editor').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.find(layer => layer.name === '成交记录').text, '213.00  →  231.00');
  let renamedPriceRow = nodes.get('editor-layers').children.find(row => row.children[0].textContent.includes('成交记录'));
  await renamedPriceRow.children[0].fire('click');
  nodes.get('prop-binding').value = '';
  await nodes.get('prop-binding').fire('change');
  nodes.get('prop-text').value = 'KEEP THIS WORDING';
  await nodes.get('prop-text').fire('change');
  nodes.get('sell-price').value = '232';
  await nodes.get('sell-price').fire('change');
  await nodes.get('open-editor').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.find(layer => layer.name === '成交记录').text, 'KEEP THIS WORDING');
  renamedPriceRow = nodes.get('editor-layers').children.find(row => row.children[0].textContent.includes('成交记录'));
  await renamedPriceRow.children[0].fire('click');
  nodes.get('prop-binding').value = 'prices';
  await nodes.get('prop-binding').fire('change');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.find(layer => layer.name === '成交记录').text, '213.00  →  232.00');
  nodes.get('sell-price').value = '230';
  await nodes.get('sell-price').fire('change');
  await nodes.get('open-editor').fire('click');
  const priceRow = nodes.get('editor-layers').children.find(row => row.children[0].textContent.includes('成交记录'));
  await priceRow.children[0].fire('click');
  await nodes.get('layer-delete').fire('click');
  for (const [id, expected] of [['days', '2 DAYS HELD'], ['capital', 'HKD 10,000.00'], ['profit', 'HKD +798.12']]) {
    await nodes.get('editor-add-' + id).fire('click');
    assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.at(-1).text, expected);
    await nodes.get('layer-delete').fire('click');
  }
  assert.equal(nodes.get('layer-count').textContent, '6');
  nodes.get('capital').value = '';
  await nodes.get('capital').fire('input');
  await nodes.get('open-editor').fire('click');
  assert.equal(nodes.get('editor-add-capital').disabled, true);
  assert.equal(nodes.get('editor-add-profit').disabled, true);
  nodes.get('capital').value = '10000';
  await nodes.get('capital').fire('input');
  await nodes.get('open-editor').fire('click');
  assert.equal(nodes.get('editor-add-capital').disabled, false);
  await nodes.get('editor-add-text').fire('click');
  assert.equal(nodes.get('layer-count').textContent, '7');
  await nodes.get('align-right').fire('click');
  await nodes.get('align-bottom').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.at(-1).x, 320);
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.at(-1).y, 1070);
  await nodes.get('editor-undo').fire('click');
  await nodes.get('editor-undo').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.at(-1).x, 160);
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.at(-1).y, 400);
  nodes.get('prop-rotation').value = '90';
  await nodes.get('prop-rotation').fire('change');
  await nodes.get('align-right').fire('click');
  await nodes.get('align-top').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.at(-1).x, 570);
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.at(-1).y, 250);
  await nodes.get('editor-undo').fire('click');
  await nodes.get('editor-undo').fire('click');
  await nodes.get('editor-undo').fire('click');
  nodes.get('prop-text').value = 'ONE GOOD TRADE';
  await nodes.get('prop-text').fire('change');
  assert.ok(JSON.parse(storage.get('yink.editor.v1')).layers.some(layer => layer.text === 'ONE GOOD TRADE'));
  await nodes.get('editor-undo').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.at(-1).text, 'YOUR MOMENT.');
  await nodes.get('editor-redo').fire('click');
  nodes.get('prop-text-fit').value = 'fixed';
  await nodes.get('prop-text-fit').fire('change');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.at(-1).textFit, 'fixed');
  await nodes.get('layer-duplicate').fire('click');
  assert.equal(nodes.get('layer-count').textContent, '8');
  await nodes.get('layer-delete').fire('click');
  assert.equal(nodes.get('layer-count').textContent, '7');
  await ratioNodes.find(node => node.dataset.ratio === 'A4').fire('click');
  await ratioNodes.find(node => node.dataset.ratio === 'A4').fire('click');
  await nodes.get('editor-undo').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).ratio, '4:5');
  await nodes.get('editor-redo').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).ratio, 'A4');
  await nodes.get('ratio-landscape').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).ratio, 'A4-landscape');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).height, 707);
  assert.equal(nodes.get('ratio-label-share').textContent, '5:4');
  assert.equal(nodes.get('ratio-label-story').textContent, '16:9');
  assert.equal(nodes.get('ratio-label-a4').textContent, 'A4 横');
  nodes.get('editor-export-width').value = '2480';
  await nodes.get('editor-export-width').fire('change');
  await nodes.get('editor-export').fire('click');
  assert.match(downloaded, /YINK-artwork-A4-landscape\.png/);
  assert.match(nodes.get('editor-status').textContent, /3508 × 2480 PNG/);
  nodes.get('editor-export-width').value = '1920';
  await nodes.get('editor-export-width').fire('change');
  await ratioNodes.find(node => node.dataset.ratio === '4:5').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).ratio, '5:4');
  await ratioNodes.find(node => node.dataset.ratio === '9:16').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).ratio, '16:9');
  await nodes.get('editor-export').fire('click');
  assert.match(nodes.get('editor-status').textContent, /1920 × 1080 PNG/);
  await nodes.get('ratio-portrait').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).ratio, '9:16');
  await ratioNodes.find(node => node.dataset.ratio === 'A4').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).ratio, 'A4');
  nodes.get('ratio-width').value = '16';
  nodes.get('ratio-height').value = '9';
  await nodes.get('ratio-apply').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).ratio, 'custom');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).height, 563);
  assert.equal(nodes.get('editor-dimensions').textContent, '1000 × 563');
  nodes.get('ratio-width').value = '1';
  nodes.get('ratio-height').value = '5';
  await nodes.get('ratio-apply').fire('click');
  assert.match(nodes.get('ratio-status').textContent, /宽高比限/);
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).height, 563);
  await nodes.get('editor-undo').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).ratio, 'A4');
  await nodes.get('editor-redo').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).ratio, 'custom');
  await nodes.get('editor-export').fire('click');
  assert.match(downloaded, /YINK-artwork-custom\.png/);
  assert.match(nodes.get('editor-status').textContent, /1920 × 1080 PNG/);
  const customProject = storage.get('yink.editor.v1');
  nodes.get('editor-open-project').files = [{ size: customProject.length, text: async () => customProject }];
  await nodes.get('editor-open-project').fire('change');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).ratio, 'custom');
  assert.equal(nodes.get('ratio-width').value, '16');
  assert.equal(nodes.get('ratio-height').value, '9');
  await ratioNodes.find(node => node.dataset.ratio === 'A4').fire('click');
  const klineRow = nodes.get('editor-layers').children.find(row => row.children[0].textContent.includes('交易 K 线'));
  await klineRow.children[0].fire('click');
  assert.equal(nodes.get('kline-properties').hidden, false);
  assert.equal(nodes.get('kline-advanced-panel').hidden, false);
  nodes.get('prop-kline-mode').value = 'area';
  await nodes.get('prop-kline-mode').fire('change');
  nodes.get('prop-kline-up').value = '#ff5500';
  await nodes.get('prop-kline-up').fire('change');
  nodes.get('prop-kline-labels').checked = false;
  await nodes.get('prop-kline-labels').fire('change');
  nodes.get('prop-kline-buy-marker').value = 'image';
  await nodes.get('prop-kline-buy-marker').fire('change');
  assert.match(nodes.get('editor-status').textContent, /请先上传/);
  nodes.get('prop-kline-buy-marker').value = 'diamond';
  await nodes.get('prop-kline-buy-marker').fire('change');
  nodes.get('prop-kline-profit-mode').value = 'dashed';
  await nodes.get('prop-kline-profit-mode').fire('change');
  const styled = JSON.parse(storage.get('yink.editor.v1')).layers.find(layer => layer.type === 'kline');
  assert.equal(styled.style.mode, 'area');
  assert.equal(styled.style.up, '#ff5500');
  assert.equal(styled.style.labels, false);
  assert.equal(styled.style.buyMarker, 'diamond');
  assert.equal(styled.style.profitMode, 'dashed');
  await nodes.get('editor-add-kline').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.at(-1).style.mode, 'area');
  nodes.get('sell-price').value = '232';
  await nodes.get('sell-price').fire('change');
  await nodes.get('open-editor').fire('click');
  const updatedKlines = JSON.parse(storage.get('yink.editor.v1')).layers.filter(layer => layer.type === 'kline');
  assert.equal(updatedKlines.length, 2);
  assert.ok(updatedKlines.every(layer => layer.trade.sell.price === 232));
  assert.equal(updatedKlines[1].style.mode, 'area');
  nodes.get('sell-price').value = '230';
  await nodes.get('sell-price').fire('change');
  await nodes.get('open-editor').fire('click');
  const secondKlineRow = nodes.get('editor-layers').children.find(row => row.children[0].textContent.includes('K 线贴图'));
  await secondKlineRow.children[0].fire('click');
  await nodes.get('layer-delete').fire('click');
  const beforeBrokenImage = storage.get('yink.editor.v1');
  nodes.get('editor-add-image').files = [{ type: 'image/png', size: 100, data: 'data:image/png;base64,CORRUPT' }];
  await nodes.get('editor-add-image').fire('change');
  assert.equal(storage.get('yink.editor.v1'), beforeBrokenImage);
  assert.match(nodes.get('editor-status').textContent, /图片文件无法解码/);
  const localImage = { type: 'image/png', size: 100, data: 'data:image/png;base64,AAAA' };
  nodes.get('editor-bg-image').files = [localImage];
  await nodes.get('editor-bg-image').fire('change');
  assert.equal(nodes.get('editor-bg-fit').disabled, false);
  nodes.get('editor-bg-focus-x').value = '100';
  await nodes.get('editor-bg-focus-x').fire('change');
  nodes.get('editor-bg-focus-y').value = '0';
  await nodes.get('editor-bg-focus-y').fire('change');
  nodes.get('editor-bg-fit').value = 'contain';
  await nodes.get('editor-bg-fit').fire('change');
  assert.equal(nodes.get('editor-bg-focus-x').disabled, true);
  nodes.get('editor-add-image').files = [localImage];
  await nodes.get('editor-add-image').fire('change');
  assert.equal(nodes.get('image-properties').hidden, false);
  const imageBefore = JSON.parse(storage.get('yink.editor.v1')).layers.at(-1);
  nodes.get('prop-image-focus-x').value = '0';
  await nodes.get('prop-image-focus-x').fire('change');
  nodes.get('prop-image-focus-y').value = '100';
  await nodes.get('prop-image-focus-y').fire('change');
  nodes.get('prop-image-fit').value = 'contain';
  await nodes.get('prop-image-fit').fire('change');
  assert.equal(nodes.get('prop-image-focus-x').disabled, true);
  const replacement = { type: 'image/jpeg', size: 120, data: 'data:image/jpeg;base64,BBBB' };
  nodes.get('prop-image-replace').files = [replacement];
  await nodes.get('prop-image-replace').fire('change');
  const textRow = nodes.get('editor-layers').children.find(row => row.children[0].textContent.includes('品牌'));
  await textRow.children[0].fire('click');
  assert.equal(nodes.get('prop-font-size').value, '22');
  assert.equal(nodes.get('prop-font-size-number').value, '22');
  nodes.get('prop-font-size').value = '40';
  await nodes.get('prop-font-size').fire('input');
  nodes.get('prop-font-size').value = '48';
  await nodes.get('prop-font-size').fire('input');
  assert.equal(nodes.get('font-size-value').textContent, '48 px');
  assert.equal(nodes.get('prop-font-size-number').value, '48');
  await nodes.get('prop-font-size').fire('change');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.find(layer => layer.name === '品牌').fontSize, 48);
  await nodes.get('editor-undo').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.find(layer => layer.name === '品牌').fontSize, 22);
  await nodes.get('editor-redo').fire('click');
  assert.equal(nodes.get('prop-font-size').value, '48');
  nodes.get('prop-font-size-number').value = '55';
  await nodes.get('prop-font-size-number').fire('change');
  assert.equal(nodes.get('prop-font-size').value, '55');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.find(layer => layer.name === '品牌').fontSize, 55);
  nodes.get('prop-font').value = 'noto-sans-sc';
  await nodes.get('prop-font').fire('change');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.find(layer => layer.name === '品牌').font, 'noto-sans-sc');
  nodes.get('prop-font').value = 'long-cang';
  await nodes.get('prop-font').fire('change');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.find(layer => layer.name === '品牌').font, 'long-cang');
  const beforeBadFont = storage.get('yink.editor.v1');
  nodes.get('prop-font-upload').files = [{ name: 'bad.ttf', size: 100, data: 'data:font/ttf;base64,CORRUPT' }];
  await nodes.get('prop-font-upload').fire('change');
  assert.equal(storage.get('yink.editor.v1'), beforeBadFont);
  assert.match(nodes.get('editor-status').textContent, /字体文件无法加载/);
  nodes.get('prop-font-upload').files = [{ name: 'My Font.ttf', size: 100, data: 'data:application/octet-stream;base64,AAAA' }];
  await nodes.get('prop-font-upload').fire('change');
  const customFontLayer = JSON.parse(storage.get('yink.editor.v1')).layers.find(layer => layer.name === '品牌');
  assert.equal(customFontLayer.font, 'custom');
  assert.equal(customFontLayer.fontData, 'data:font/ttf;base64,AAAA');
  assert.equal(customFontLayer.fontName, 'My Font.ttf');
  assert.match(nodes.get('prop-font-note').textContent, /My Font.ttf/);
  const project = storage.get('yink.editor.v1');
  assert.equal(JSON.parse(project).background.image, localImage.data);
  assert.equal(JSON.parse(project).background.fit, 'contain');
  assert.equal(JSON.parse(project).background.focusX, 100);
  assert.equal(JSON.parse(project).background.focusY, 0);
  assert.ok(JSON.parse(project).layers.some(layer => layer.type === 'image' && layer.src === replacement.data && layer.fit === 'contain' && layer.focusX === 0 && layer.focusY === 100 && layer.x === imageBefore.x && layer.y === imageBefore.y));
  await nodes.get('editor-save-project').fire('click');
  assert.equal(downloaded, 'YINK-project.json');
  await nodes.get('editor-add-rect').fire('click');
  assert.notEqual(storage.get('yink.editor.v1'), project);
  nodes.get('editor-open-project').files = [{ size: project.length, text: async () => project }];
  await nodes.get('editor-open-project').fire('change');
  assert.equal(storage.get('yink.editor.v1'), project);
  nodes.get('editor-section').hidden = true;
  nodes.get('open-project-entry').files = [{ size: project.length, text: async () => project }];
  await nodes.get('open-project-entry').fire('change');
  assert.equal(nodes.get('editor-section').hidden, false);
  const legacyDesign = JSON.parse(project);
  legacyDesign.layers.filter(layer => layer.type === 'text').forEach(layer => { delete layer.binding; });
  const legacyProject = JSON.stringify(legacyDesign);
  nodes.get('editor-open-project').files = [{ size: legacyProject.length, text: async () => legacyProject }];
  await nodes.get('editor-open-project').fire('change');
  const legacyReturnRow = nodes.get('editor-layers').children.find(row => row.children[0].textContent.includes('收益率'));
  await legacyReturnRow.children[0].fire('click');
  assert.equal(nodes.get('prop-binding').value, 'returnPct');
  nodes.get('sell-price').value = '234';
  await nodes.get('sell-price').fire('change');
  await nodes.get('open-editor').fire('click');
  const migratedReturn = JSON.parse(storage.get('yink.editor.v1')).layers.find(layer => layer.name === '收益率');
  assert.equal(migratedReturn.binding, 'returnPct');
  assert.equal(migratedReturn.text, '+9.86%');
  nodes.get('sell-price').value = '230';
  await nodes.get('sell-price').fire('change');
  nodes.get('editor-open-project').files = [{ size: project.length, text: async () => project }];
  await nodes.get('editor-open-project').fire('change');
  assert.equal(storage.get('yink.editor.v1'), project);
  const brokenProject = JSON.stringify({ ...JSON.parse(project), background: 'broken' });
  nodes.get('open-project-entry').files = [{ size: brokenProject.length, text: async () => brokenProject }];
  await nodes.get('open-project-entry').fire('change');
  assert.equal(storage.get('yink.editor.v1'), project);
  assert.match(nodes.get('editor-status').textContent, /背景格式/);
  assert.match(nodes.get('project-entry-status').textContent, /背景格式/);
  const brokenImageProject = JSON.stringify({ ...JSON.parse(project), background: { color: '#f5f2e9', image: 'data:image/png;base64,CORRUPT' } });
  nodes.get('open-project-entry').files = [{ size: brokenImageProject.length, text: async () => brokenImageProject }];
  await nodes.get('open-project-entry').fire('change');
  assert.equal(storage.get('yink.editor.v1'), project);
  assert.match(nodes.get('project-entry-status').textContent, /本地图片无法解码/);
  let finishOlderRead;
  const olderProject = JSON.stringify({ ...JSON.parse(project), background: { color: '#171a1a', image: null } });
  nodes.get('open-project-entry').files = [{ size: olderProject.length, text: () => new Promise(resolve => { finishOlderRead = resolve; }) }];
  const olderOpen = nodes.get('open-project-entry').fire('change');
  nodes.get('open-project-entry').files = [{ size: project.length, text: async () => project }];
  await nodes.get('open-project-entry').fire('change');
  finishOlderRead(olderProject);
  await olderOpen;
  assert.equal(storage.get('yink.editor.v1'), project);
  const delayedBackground = { ...localImage, defer: true };
  const delayedSticker = { ...localImage, defer: true };
  nodes.get('editor-bg-image').files = [delayedBackground];
  nodes.get('editor-add-image').files = [delayedSticker];
  const pendingBackground = nodes.get('editor-bg-image').fire('change');
  const pendingSticker = nodes.get('editor-add-image').fire('change');
  nodes.get('open-project-entry').files = [{ size: project.length, text: async () => project }];
  await nodes.get('open-project-entry').fire('change');
  delayedBackground.finish();
  delayedSticker.finish();
  await Promise.all([pendingBackground, pendingSticker]);
  assert.equal(storage.get('yink.editor.v1'), project);
  nodes.get('editor-export-width').value = '2480';
  await nodes.get('editor-export-width').fire('change');
  const originalRender = window.YINK.EditorRender.render;
  let exportArgs;
  window.YINK.EditorRender.render = async (...args) => { exportArgs = args; return originalRender(...args); };
  await nodes.get('editor-export').fire('click');
  assert.match(downloaded, /YINK-artwork-A4\.png/);
  assert.equal(exportArgs[2], 2480);
  assert.equal(exportArgs[3], 3508);
  assert.equal(exportArgs[4], null);
  assert.equal(exportArgs[5], false);
  assert.equal(exportArgs[1].background.focusX, 100);
  assert.equal(exportArgs[1].layers.find(layer => layer.type === 'image').focusY, 100);
  let finishExport;
  window.YINK.EditorRender.render = async (...args) => {
    exportArgs = args;
    await new Promise(resolve => { finishExport = resolve; });
    return originalRender(...args);
  };
  const pendingExport = nodes.get('editor-export').fire('click');
  const frozenLayerCount = exportArgs[1].layers.length;
  await nodes.get('editor-add-rect').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.length, frozenLayerCount + 1);
  finishExport();
  await pendingExport;
  assert.equal(exportArgs[1].layers.length, frozenLayerCount);
  window.YINK.EditorRender.render = originalRender;
  await nodes.get('editor-add-text').fire('click');
  for (let index = 0; index < 65; index++) {
    nodes.get('prop-name').value = '文字 ' + index;
    await nodes.get('prop-name').fire('change');
  }
  for (let index = 0; index < 60; index++) await nodes.get('editor-undo').fire('click');
  assert.equal(nodes.get('editor-undo').disabled, true);
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.at(-1).name, '文字 4');
  for (let index = 0; index < 60; index++) await nodes.get('editor-redo').fire('click');
  assert.equal(nodes.get('editor-redo').disabled, true);
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.at(-1).name, '文字 64');
  const imageRow = nodes.get('editor-layers').children.find(row => row.children[0].textContent.includes('图片贴图'));
  await imageRow.children[0].fire('click');
  const writeDraft = window.localStorage.setItem;
  window.localStorage.setItem = (key, value) => { if (key === 'yink.editor.v1') throw new Error('quota'); writeDraft(key, value); };
  nodes.get('prop-image-replace').files = [localImage];
  await nodes.get('prop-image-replace').fire('change');
  assert.match(nodes.get('editor-status').textContent, /本地存储空间不足/);
  nodes.get('open-project-entry').files = [{ size: project.length, text: async () => project }];
  await nodes.get('open-project-entry').fire('change');
  assert.match(nodes.get('project-entry-status').textContent, /无法自动保存/);
  await nodes.get('editor-save-project').fire('click');
  assert.equal(downloaded, 'YINK-project.json');
  window.localStorage.setItem = writeDraft;
  assert.ok(storage.has('yink.session.v1'));
  assert.equal(JSON.parse(storage.get('yink.session.v1')).events.find(event => event.type === 'SELL').price, 230);
  assert.equal(JSON.parse(storage.get('yink.session.v1')).data.security.currency, 'HKD');
  const oldSellRow = nodes.get('trade-events').children.find(row => row.children[0].children[0].textContent.startsWith('SELL'));
  await oldSellRow.children[3].fire('click');
  await canvas.fire('pointerdown', { offsetX: 500 });
  await canvas.fire('pointerup', { offsetX: 500 });
  await nodes.get('mark-sell').fire('click');
  const segment = window.YINK.getTradeSnapshot().bars;
  assert.equal(segment.length, 2);
  assert.equal(segment[0].date, '2026-09-01');
  assert.equal(segment[1].date, '2026-09-02');
  assert.equal(window.YINK.getTradeSnapshot({ mode: 'range' }).bars.length, 3);
  assert.throws(() => window.YINK.getTradeSnapshot({ mode: 'custom', start: '2026-09-02', end: '2026-09-03' }), /包含所有买卖节点/);
  for (const [index, quantity] of [10, 5].entries()) {
    const input = nodes.get('trade-events').children[index].children[2].children[0];
    input.value = String(quantity);
    await input.fire('change');
  }
  const loadedRangeTrade = window.YINK.getTradeSnapshot({ mode: 'range' }).trade;
  const croppedTrade = window.YINK.getTradeSnapshot({ mode: 'custom', start: '2026-09-01', end: '2026-09-02' }).trade;
  assert.equal(loadedRangeTrade.endDate, '2026-09-03');
  assert.equal(croppedTrade.endDate, '2026-09-02');
  assert.equal(croppedTrade.remainingQuantity, 5);
  assert.equal(croppedTrade.profit - loadedRangeTrade.profit, 10);
  for (let index = 0; index < 2; index++) {
    const input = nodes.get('trade-events').children[index].children[2].children[0];
    input.value = '';
    await input.fire('change');
  }
  await nodes.get('make-poster').fire('click');
  nodes.get('kline-crop').value = 'custom';
  nodes.get('kline-crop-start').value = '2026-09-02';
  nodes.get('kline-crop-end').value = '2026-09-03';
  await nodes.get('kline-crop').fire('change');
  assert.match(nodes.get('kline-style-status').textContent, /包含所有买卖节点/);
  nodes.get('kline-crop').value = 'range';
  await nodes.get('kline-crop').fire('change');
  await nodes.get('open-editor').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.find(layer => layer.type === 'kline').bars.length, 3);
  await nodes.get('editor-add-rect').fire('click');
  const artCanvas = nodes.get('editor-canvas');
  let pointerDesign = JSON.parse(storage.get('yink.editor.v1'));
  const initialRect = pointerDesign.layers.at(-1);
  const pointerAt = (x, y) => ({ clientX: x * 900 / pointerDesign.width, clientY: y * 430 / pointerDesign.height });
  const centerX = initialRect.x + initialRect.w / 2;
  const centerY = initialRect.y + initialRect.h / 2;
  const mobilePanels = [];
  window.YINK.MobileUI = { canDrag: () => false, isMobile: () => true, showPanel: name => mobilePanels.push(name) };
  const touchAt = (x, y) => ({ ...pointerAt(x, y), pointerType: 'touch', isPrimary: true });
  const beforeSwipe = storage.get('yink.editor.v1');
  await artCanvas.fire('pointerdown', touchAt(centerX, centerY));
  await artCanvas.fire('pointermove', touchAt(centerX, centerY + 100));
  await artCanvas.fire('pointerup', touchAt(centerX, centerY + 100));
  assert.equal(storage.get('yink.editor.v1'), beforeSwipe);
  assert.deepEqual(mobilePanels, [], 'Scrolling across canvas must not open properties');
  await artCanvas.fire('pointerdown', touchAt(centerX, centerY));
  await artCanvas.fire('pointercancel', touchAt(centerX, centerY));
  assert.deepEqual(mobilePanels, [], 'Cancelled touch must not select a module');
  await artCanvas.fire('pointerdown', touchAt(centerX, centerY));
  await artCanvas.fire('pointerup', touchAt(centerX, centerY));
  assert.deepEqual(mobilePanels, ['layers']);
  assert.equal(storage.get('yink.editor.v1'), beforeSwipe, 'Selection alone must not change the artwork');
  window.YINK.MobileUI.canDrag = () => true;
  await artCanvas.fire('pointerdown', pointerAt(centerX, centerY));
  await artCanvas.fire('pointerdown', { ...pointerAt(centerX, centerY), pointerId: 2 });
  await artCanvas.fire('pointermove', { ...pointerAt(centerX + 100, centerY + 100), pointerId: 2 });
  await artCanvas.fire('pointerup', { ...pointerAt(centerX + 100, centerY + 100), pointerId: 2 });
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.at(-1).x, initialRect.x);
  await artCanvas.fire('pointermove', pointerAt(centerX + 20, centerY + 30));
  await artCanvas.fire('pointerup', pointerAt(centerX + 20, centerY + 30));
  pointerDesign = JSON.parse(storage.get('yink.editor.v1'));
  const movedRect = pointerDesign.layers.at(-1);
  assert.equal(movedRect.x, initialRect.x + 20);
  assert.equal(movedRect.y, initialRect.y + 30);
  const cornerX = movedRect.x + movedRect.w;
  const cornerY = movedRect.y;
  await artCanvas.fire('pointerdown', pointerAt(cornerX, cornerY));
  await artCanvas.fire('pointermove', pointerAt(cornerX + 40, cornerY - 20));
  await artCanvas.fire('pointerup', pointerAt(cornerX + 40, cornerY - 20));
  pointerDesign = JSON.parse(storage.get('yink.editor.v1'));
  const resizedRect = pointerDesign.layers.at(-1);
  assert.equal(resizedRect.x, movedRect.x);
  assert.equal(resizedRect.y, movedRect.y - 20);
  assert.equal(resizedRect.w, movedRect.w + 40);
  assert.equal(resizedRect.h, movedRect.h + 20);
  const touchCenterX = resizedRect.x + resizedRect.w / 2;
  const touchCenterY = resizedRect.y + resizedRect.h / 2;
  await artCanvas.fire('pointerdown', touchAt(touchCenterX, touchCenterY));
  await artCanvas.fire('pointermove', touchAt(touchCenterX + 20, touchCenterY + 20));
  await artCanvas.fire('pointerup', touchAt(touchCenterX + 20, touchCenterY + 20));
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.at(-1).x, resizedRect.x + 20, 'Touch drag must work when enabled');
  delete window.YINK.MobileUI;
  const alternateCsv = 'date,open,high,low,close,volume\n2026-09-01,40,42,39,41,100\n2026-09-02,41,46,40,44,120\n2026-09-03,44,49,43,48,110';
  nodes.get('csv-file').files = [{ size: alternateCsv.length, text: async () => alternateCsv }];
  await nodes.get('csv-file').fire('change');
  await nodes.get('load-button').fire('click');
  assert.match(nodes.get('editor-status').textContent, /上一作品/);
  await canvas.fire('pointerdown', { offsetX: 80 });
  await canvas.fire('pointerup', { offsetX: 80 });
  await nodes.get('mark-buy').fire('click');
  await canvas.fire('pointerdown', { offsetX: 800 });
  await canvas.fire('pointerup', { offsetX: 800 });
  await nodes.get('mark-sell').fire('click');
  await nodes.get('make-poster').fire('click');
  await nodes.get('open-editor').fire('click');
  const alternateArtwork = JSON.parse(storage.get('yink.editor.v1'));
  assert.equal(alternateArtwork.layers.length, 6);
  assert.equal(alternateArtwork.background.image, null);
  assert.notEqual(alternateArtwork.source.identity, JSON.parse(project).source.identity);
  await nodes.get('editor-undo').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).background.image, localImage.data);
  await nodes.get('editor-redo').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).background.image, null);
  await canvas.fire('pointerdown', { offsetX: 500 });
  await canvas.fire('pointerup', { offsetX: 500 });
  await nodes.get('mark-buy').fire('click');
  assert.equal(nodes.get('make-poster').disabled, true);
  for (const [index, quantity] of [10, 5, 8].entries()) {
    const input = nodes.get('trade-events').children[index].children[2].children[0];
    input.value = String(quantity);
    await input.fire('change');
  }
  assert.equal(nodes.get('make-poster').disabled, false);
  const multipleSnapshot = window.YINK.getTradeSnapshot();
  assert.equal(multipleSnapshot.trade.events.length, 3);
  assert.equal(multipleSnapshot.trade.remainingQuantity, 7);
  assert.equal(multipleSnapshot.trade.realizedProfit, 48);
  assert.equal(multipleSnapshot.trade.unrealizedProfit, 42);
  await nodes.get('make-poster').fire('click');
  nodes.get('kline-buy-marker-image').files = [{ type: 'image/png', size: 100, data: 'data:image/png;base64,BBBB' }];
  await nodes.get('kline-buy-marker-image').fire('change');
  assert.equal(nodes.get('kline-buy-marker').value, 'image');
  assert.match(nodes.get('kline-style-status').textContent, /BUY 标点图片已读取/);
  nodes.get('kline-profit-mode').value = 'red';
  await nodes.get('kline-profit-mode').fire('input');
  nodes.get('kline-stroke-width').value = '1.5';
  await nodes.get('kline-stroke-width').fire('input');
  await nodes.get('open-editor').fire('click');
  const multipleLayer = JSON.parse(storage.get('yink.editor.v1')).layers.find(layer => layer.type === 'kline');
  assert.equal(multipleLayer.trade.events.length, 3);
  assert.equal(multipleLayer.style.buyMarkerImage, 'data:image/png;base64,BBBB');
  assert.equal(multipleLayer.style.profitMode, 'red');
  assert.equal(multipleLayer.style.strokeWidth, 1.5);
  const advancedProject = storage.get('yink.editor.v1');
  nodes.get('open-project-entry').files = [{ size: advancedProject.length, text: async () => advancedProject }];
  await nodes.get('open-project-entry').fire('change');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).layers.find(layer => layer.type === 'kline').style.buyMarker, 'image');
  await nodes.get('editor-export').fire('click');
  assert.match(downloaded, /^YINK-artwork-/);
  const hourlyCsv = 'date,open,high,low,close,volume\n2026-09-01 09:30,40,42,39,41,10\n2026-09-01 10:30,41,45,40,44,12\n2026-09-01 11:30,44,49,43,48,11';
  nodes.get('csv-file').files = [{ size: hourlyCsv.length, text: async () => hourlyCsv }];
  await nodes.get('csv-file').fire('change');
  nodes.get('kline-interval').value = 'auto';
  await nodes.get('kline-interval').fire('change');
  await nodes.get('load-button').fire('click');
  assert.equal(window.YINK.currentData.interval, 'hour');
  assert.equal(window.YINK.currentData.bars[0].date, '2026-09-01 09:30');
  await canvas.fire('pointerdown', { offsetX: 80 });
  await canvas.fire('pointerup', { offsetX: 80 });
  await nodes.get('mark-buy').fire('click');
  await canvas.fire('pointerdown', { offsetX: 800 });
  await canvas.fire('pointerup', { offsetX: 800 });
  await nodes.get('mark-sell').fire('click');
  const hourlySnapshot = window.YINK.getTradeSnapshot();
  assert.equal(hourlySnapshot.trade.holdingHours, 2);
  await nodes.get('make-poster').fire('click');
  await nodes.get('open-editor').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).source.trade.holdingHours, 2);
  const hourlySell = nodes.get('trade-events').children.find(row => row.children[0].children[0].textContent.startsWith('SELL'));
  await hourlySell.children[3].fire('click');
  await canvas.fire('pointerdown', { offsetX: 80 });
  await canvas.fire('pointerup', { offsetX: 80 });
  await nodes.get('mark-sell').fire('click');
  for (let index = 0; index < 2; index++) {
    const input = nodes.get('trade-events').children[index].children[2].children[0];
    input.value = '2';
    await input.fire('change');
  }
  const sameCandleSnapshot = window.YINK.getTradeSnapshot();
  assert.equal(sameCandleSnapshot.bars.length, 2);
  assert.equal(sameCandleSnapshot.trade.buy.date, sameCandleSnapshot.trade.sell.date);
  canvas.arcCalls.length = 0;
  await nodes.get('zoom-reset').fire('click');
  assert.equal(canvas.arcCalls.length, 2);
  assert.notEqual(canvas.arcCalls[0][1], canvas.arcCalls[1][1]);
  await nodes.get('make-poster').fire('click');
  await nodes.get('open-editor').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).source.trade.buy.date, JSON.parse(storage.get('yink.editor.v1')).source.trade.sell.date);
  const minuteCsv = 'date,open,high,low,close,volume\n2026-09-01 09:30,40,42,39,41,10\n2026-09-01 09:35,41,45,40,44,12\n2026-09-01 09:40,44,49,43,48,11';
  nodes.get('csv-file').files = [{ size: minuteCsv.length, text: async () => minuteCsv }];
  await nodes.get('csv-file').fire('change');
  nodes.get('kline-interval').value = 'auto';
  await nodes.get('kline-interval').fire('change');
  await nodes.get('load-button').fire('click');
  assert.equal(window.YINK.currentData.interval, 'minute5');
  assert.equal(nodes.get('bar-count-label').textContent, '5-MIN BARS');
  assert.equal(nodes.get('time-range-row').hidden, false);
  nodes.get('start-time').value = '09:34';
  await nodes.get('start-time').fire('change');
  nodes.get('end-time').value = '09:37';
  await nodes.get('end-time').fire('change');
  await nodes.get('load-button').fire('click');
  assert.equal(window.YINK.currentData.interval, 'minute5');
  assert.equal(window.YINK.currentData.bars.length, 1);
  assert.match(nodes.get('status').textContent, /至少需要两根 K 线/);
  nodes.get('end-time').value = '09:40';
  await nodes.get('end-time').fire('change');
  await nodes.get('load-button').fire('click');
  assert.deepEqual(Array.from(window.YINK.currentData.bars, bar => bar.date), ['2026-09-01 09:35', '2026-09-01 09:40']);
  await canvas.fire('pointerdown', { offsetX: 80 });
  await canvas.fire('pointerup', { offsetX: 80 });
  await nodes.get('mark-buy').fire('click');
  await canvas.fire('pointerdown', { offsetX: 800 });
  await canvas.fire('pointerup', { offsetX: 800 });
  await nodes.get('mark-sell').fire('click');
  assert.equal(window.YINK.getTradeSnapshot().trade.holdingMinutes, 5);
  await nodes.get('make-poster').fire('click');
  await nodes.get('open-editor').fire('click');
  assert.equal(JSON.parse(storage.get('yink.editor.v1')).source.trade.holdingMinutes, 5);
  await nodes.get('editor-export').fire('click');
  assert.match(downloaded, /^YINK-artwork-/);
  const savedMinute = JSON.parse(storage.get('yink.session.v1')).data;
  assert.equal(savedMinute.range.startTime, '09:34');
  assert.equal(savedMinute.range.endTime, '09:40');
  assert.throws(() => window.YINK.restoreSessionData({ ...savedMinute, range: { ...savedMinute.range, endTime: '09:36' } }), /时刻区间与 K 线不一致/);
  window.YINK.restoreSessionData(savedMinute);
  assert.equal(window.YINK.currentData.interval, 'minute5');
  assert.equal(window.YINK.currentData.bars.length, 2);
  assert.equal(nodes.get('start-time').value, '09:34');
  function reloadEditor() {
    const fresh = new Map(Array.from(ids, id => [id, new FakeNode('element', id)]));
    context.document = {
      getElementById: id => fresh.get(id) || null,
      createElement: tag => new FakeNode(tag),
      createTextNode: value => { const node = new FakeNode('text'); node.textContent = value; return node; },
      createDocumentFragment: () => new FakeNode('fragment'),
      querySelectorAll: selector => selector === '[data-ratio]' ? ratioNodes : selector === '[data-bg]' ? backgroundNodes : [],
      fonts: { add() {} }, head: new FakeNode('head'), body: new FakeNode('body')
    };
    vm.runInContext(fs.readFileSync(path.join(root, 'js/editor/ui.js'), 'utf8'), context, { filename: 'js/editor/ui.js' });
    return fresh;
  }
  storage.set('yink.editor.v1', project);
  const restoredNodes = reloadEditor();
  await new Promise(resolve => setImmediate(resolve));
  assert.equal(restoredNodes.get('editor-section').hidden, false);
  assert.match(restoredNodes.get('editor-status').textContent, /已恢复/);
  assert.match(restoredNodes.get('editor-status').textContent, /与当前行情不同/);
  const presetButtons = restoredNodes.get('editor-sticker-presets').children;
  assert.equal(presetButtons.length, 5);
  const logoPreview = decodeURIComponent(window.YINK.EditorStickers.preview('yink-logo').split(',')[1]);
  assert.doesNotMatch(logoPreview, /<text\b|M256 200h292/);
  for (const button of presetButtons) await button.fire('click');
  const stickerDesign = JSON.parse(storage.get('yink.editor.v1'));
  const stickerLayers = stickerDesign.layers.filter(layer => layer.type === 'image' && ['墨韵 · 云染', '墨韵 · 飞溅', '墨韵 · 流痕', '墨韵 · 泼墨背景', '盈刻 Logo'].includes(layer.name));
  assert.deepEqual(stickerLayers.map(layer => layer.name), ['墨韵 · 泼墨背景', '墨韵 · 云染', '墨韵 · 飞溅', '墨韵 · 流痕', '盈刻 Logo']);
  assert.ok(stickerLayers.every(layer => /^data:image\/(png|webp);base64,/.test(layer.src) && layer.fit === 'contain'));
  assert.equal(stickerDesign.layers[0].name, '墨韵 · 泼墨背景');
  assert.ok(stickerDesign.layers.findIndex(layer => layer.type === 'kline') > 0);
  assert.equal(window.YINK.EditorModel.validateDesign(stickerDesign).layers.length, JSON.parse(project).layers.length + 5);
  downloaded = '';
  await restoredNodes.get('editor-export').fire('click');
  assert.match(downloaded, /^YINK-artwork-/);
  const corruptDraft = JSON.stringify({ ...JSON.parse(project), background: { color: '#f5f2e9', image: 'data:image/png;base64,CORRUPT' } });
  storage.set('yink.editor.v1', corruptDraft);
  const failedNodes = reloadEditor();
  await new Promise(resolve => setImmediate(resolve));
  assert.equal(storage.has('yink.editor.v1'), false);
  assert.match(failedNodes.get('project-entry-status').textContent, /草稿无法恢复/);
  console.log('UI flow test passed');
})().catch(error => { console.error(error); process.exitCode = 1; });
